### ISSUE TITLE
All links broken

### ISSUE THREAD

**Issue by flashgrimmie** [anza-xyz/wallet-adapter#921]
**Describe the bug**
All links are broken in https://anza-xyz.github.io/wallet-adapter/

**To Reproduce**
1. Go to https://anza-xyz.github.io/wallet-adapter/
2. Click on **TypeScript Docs**
3. See 404 error

**Expected behavior**
Would like to see the docs and demo

**Screenshots**
<img width="1283" alt="image" src="https://github.com/anza-xyz/wallet-adapter/assets/55588335/b93dffbc-396c-4784-b3f0-e83fed8ca901">

**Comment by jordaaash** [comment]
Thanks! Fixed by #922 and redeploying Github pages.

**Comment by jordaaash** [comment]
Hmm. So these are being generated and don't 404:

<img width="307" alt="Screenshot 2024-03-07 at 11 25 39 AM" src="https://github.com/anza-xyz/wallet-adapter/assets/1173161/4dfccc63-572e-43f0-9979-f58a48980b3b">

However, it's missing generated types for a bunch of stuff, e.g. https://anza-xyz.github.io/wallet-adapter/modules/_solana_wallet_adapter_base.html

**Comment by Henry-E** [comment]
> Hmm. So these are being generated and don't 404:
> 
> <img alt="Screenshot 2024-03-07 at 11 25 39 AM" width="307" src="https://private-user-images.githubusercontent.com/1173161/310979189-4dfccc63-572e-43f0-9979-f58a48980b3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NzEyNTYsIm5iZiI6MTcyOTc3MDk1NiwicGF0aCI6Ii8xMTczMTYxLzMxMDk3OTE4OS00ZGZjY2M2My01NzJlLTQzZjAtOTk3OS1mNThhNDg5ODBiM2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjRUMTE1NTU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGFlNWQyOTcyNjAxZGVmNzRlOGZkODI1MGMwOTAwOTQzMWNmNDc5YzY4ZDI2YTJjNWEyMDkxMWQxODgzYmQ4MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.qvJzvOMmnWaEfZ98ATaZ1r-ZYKbh4IiAnI0AXbpkeJw">
> However, it's missing generated types for a bunch of stuff, e.g. https://anza-xyz.github.io/wallet-adapter/modules/_solana_wallet_adapter_base.html

Just wanted to comment that every module listed here still has an empty page. So have to root around the source code to see what's available. Unless there's somewhere else this is hosted?

**Comment by mcintyre94** [comment]
TypeScript docs is still also linking to https://anza-xyz.github.io/wallet-adapter/, ie not a new page

Still seeing a 404 eg here: https://anza-xyz.github.io/wallet-adapter/modules/_solana_wallet_adapter_base.html
